name: Deploy WebdriverIO Test Automation to Github Actions

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout
          uses: actions/checkout@v2

        - uses: actions/setup-node@v1
          with:
            node-version: 16

        - name: Install
          run: npm install

        - name: Test
          run: npm run ci #### Change it as per headless CI script

        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: allure-report
            path: allure-report

        - name: Get Allure history
          uses: actions/checkout@v2
          if: always()
          continue-on-error: true
          with:
            ref: gh-pages
            path: gh-pages

        - name: Allure Report action from marketplace
          uses: simple-elf/allure-report-action@master
          if: always()
          id: allure-report
          with:
            allure_results: allure-results
            #gh_pages: gh-pages
            allure_report: allure-report
            allure_history: allure-history
            keep_reports: 20

        - name: Deploy report to Github Pages
          if: always()
          uses: peaceiris/actions-gh-pages@v2
          env:
            PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            PUBLISH_BRANCH: gh-pages
            PUBLISH_DIR: allure-history
