name: Deploy WebdriverIO Test Automation to Github Actions

on: 
  schedule:
    - cron: "0 1 * * *"
  push:
    branches:
      - master

jobs:
  test:
    name: Test Execution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        run: npm ci

      - name: Test
        run: npm run ci:chrome

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: wdio-logs
          path: wdio-logs
      
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: allure-results
          path: allure-results

  allure:
    name: Generate Allure Report
    needs: test
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: allure-results
          path: allure-results

      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        #id: allure-report
        with:
          allure_results: allure-results
          #gh_pages: gh-pages
          #allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20

      - uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
